### PR TITLE
Moving to single released version

### PR DESCRIPTION
**Pull request by chrishoffman**
Following Consul's lead on simplifying this repo to only push out a singled "supported" docker image for Vault.

### CODE REVIEW

**Comment by jefferai** [comment]
I don't have any insight into Consul's rationale for doing this, but it feels like this could have a real impact on people that want to e.g. stand up a new HA node for an existing version.

Very few pieces of software out there only have a single Docker version for exactly that reason.

**Comment by chrishoffman** [comment]
The old tags do not get removed from docker hub and are still available for use.  Since we don't backport patches into old versions of Vault there is very little reason to maintain and rebuild these old images on each release.  From the feedback I received from the official-images maintainers, this could also be part of the delay in getting updated images published.  

See this from https://github.com/docker-library/official-images#library-definition-files:
> Each library file controls the current "supported" set of image tags that appear on the Docker Hub description. Tags that are removed from a library file do not get removed from the Docker Hub, so that old versions can continue to be available for use, but are not maintained by upstream or the maintainer of the official image.

**Comment by slackpad** [comment]
@chrishoffman's comments are consistent with what I was told by the Docker folks as well. They will continue to host the old images, but the listing here is meant to signify what is supported.

**Comment by jefferai** [comment]
Sounds good!

**Pull request merged**
