### PR TITLE
Allow containers to be started without IPC_LOCK

### PR DESCRIPTION
**Pull request by ColinHebert**
Allow the container to be started without additional capabilities (see https://github.com/hashicorp/docker-vault/issues/17)

### CODE REVIEW

**Comment by jefferai** [comment]
Why not just disable mlock in your Vault config?

**Comment by ColinHebert** [comment]
mlock is disabled. The problem is that if you add the capability mlock to the binary, the container needs to be started with the mlock support in order to even start the binary.

A quick way to reproduce that would be `docker run --rm -ti vault -version`. You should get the error "error: exec failed: operation not permitted"

**Comment by jefferai** [comment]
Sure, but then you just cap-add. Why not just do that?

**Comment by jefferai** [comment]
Apparently docker swarm doesn't allow cap add, which is a much more persuasive reason to consider this than overkill.

**Comment by ColinHebert** [comment]
That makes sense. Happy to proceed to provide support for docker swarm as well.

**Comment by ColinHebert** [comment]
By the way, is there something we want to add to this Pull Request?

**Comment by ColinHebert** [comment]
Looking more into it, indeed there are cases where the entire `setcap` call will fail simply because the underlying file system doesn't support it.

**Comment by jefferai** [comment]
Merging!

**Pull request merged**
