### PR TITLE
Compatibility fix for docker swarm

### PR DESCRIPTION
**Pull request by skaczor**
This fixes an issue when using named interfaces in a docker swarm environment, which adds multiple IP addresses to each interface

### CODE REVIEW

**Comment by jefferai** [comment]
I'll get this in with the 0.7 release, thanks!

**Comment by skaczor** [comment]
Any chance we can stop using folders for revisions and use github tags instead? Currently, I can't do a valid PR until the 0.7.0 folder exists.

**Comment by jefferai** [comment]
@skaczor I don't dictate the format, Docker does. You could create a 0.7 based off of 0.6.5, or I can just merge this in once 0.7 comes out.

**Comment by jefferai** [comment]
This was put into 0.7.

**Pull request closed without merging**
