### PR TITLE
Use su-exec and tini from alpine instead of docker-base

### PR DESCRIPTION
**Pull request by issacg**
Addresses #63 

In the end I wen't with su-exec instead of gosu, as it's 1) smaller and 2) part of alpine main (gosu is in world)

### CODE REVIEW

**Comment by jefferai** [comment]
Is there a reason to use dumb-init instead of tini?

**Comment by issacg** [comment]
I wondered the same myself, as I generally use tini myself, but I changed back because 1) the projects (tini and dumb-init) seem mainly compatible (see[ the comments here](https://stackoverflow.com/questions/37374310/how-critical-is-dumb-init-for-docker), presumably written by tini's author), 2) it makes sense to be aligned with docker-consul and potentially hashicorp's other docker images, and 3) given that docker-base used dumb-init and not tini, it seemed that reverting back would make this an overall healthier PR as we're changing less tooling.

WDYT?

**Comment by jefferai** [comment]
I'm confused -- https://github.com/hashicorp/docker-consul/pull/61 says that it replaces dumb-init with alpine-native tools. How would this not be aligned with docker-consul?

**Comment by issacg** [comment]
Alpine includes dumb-init, tooOn Dec 11, 2017 7:28 PM, Jeff Mitchell <notifications@github.com> wrote:I'm confused -- hashicorp/docker-consul#61 says that it replaces dumb-init with alpine-native tools. How would this not be aligned with docker-consul?

**Comment by jefferai** [comment]
Oh, OK. Given that this PR originally wanted to use tini to use alpine tools I figured that the reason behind it was due to dumb-init not being available in Alpine.

**Pull request merged**
